// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMR-NPaoUqflgcy5MUKb5SchlXagK-bM',
    appId: '1:175213764856:web:2d7b4269ba90ac3bfbdb0d',
    messagingSenderId: '175213764856',
    projectId: 'focusecho',
    authDomain: 'focusecho.firebaseapp.com',
    storageBucket: 'focusecho.firebasestorage.app',
    measurementId: 'G-CLZBM6N9RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6bemRXX50verBcTwLZEojUA9ZmgEVno',
    appId: '1:175213764856:android:94e5f8dbea8caf72fbdb0d',
    messagingSenderId: '175213764856',
    projectId: 'focusecho',
    storageBucket: 'focusecho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRQVqsiMObqorpIZp0ZqCk4P7aem8A5w',
    appId: '1:175213764856:ios:e7b13e57e8038d42fbdb0d',
    messagingSenderId: '175213764856',
    projectId: 'focusecho',
    storageBucket: 'focusecho.firebasestorage.app',
    iosBundleId: 'com.example.focusEchoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRQVqsiMObqorpIZp0ZqCk4P7aem8A5w',
    appId: '1:175213764856:ios:e7b13e57e8038d42fbdb0d',
    messagingSenderId: '175213764856',
    projectId: 'focusecho',
    storageBucket: 'focusecho.firebasestorage.app',
    iosBundleId: 'com.example.focusEchoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCMR-NPaoUqflgcy5MUKb5SchlXagK-bM',
    appId: '1:175213764856:web:f44e3be79595320afbdb0d',
    messagingSenderId: '175213764856',
    projectId: 'focusecho',
    authDomain: 'focusecho.firebaseapp.com',
    storageBucket: 'focusecho.firebasestorage.app',
    measurementId: 'G-7RR7TJTXJB',
  );
}
